#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(optparse)
  library(Seurat)
  library(DoubletFinder)
  library(dplyr)
  library(ggplot2)
})



# =========================================================================
# Define Command-Line Arguments
# =========================================================================
option_list <- list(
  make_option(c("--project_dir"), type="character", default=NULL, help="Path to Nextflow project"),
  make_option(c("--sample_name"), type="character", default=NULL, help="Sample name"),
  make_option(c("--input_rds"), type="character", default=NULL, help="Path to raw .rds file"),
  make_option(c("--output_dir"), type="character", default="./output", help="Output directory"),
  
  make_option(c("--doublet_rate"), type="numeric", default=0.08, help="Doublet formation rate"),
  make_option(c("--min_features"), type="integer", default=200, help="Min features per cell"),
  make_option(c("--max_features"), type="integer", default=5000, help="Max features per cell"),
  make_option(c("--max_mt"), type="numeric", default=30, help="Max mitochondrial percentage"),
  make_option(c("--use_sct"), type="logical", default=TRUE, help="Use SCTransform")
)

opt_parser <- OptionParser(option_list = option_list)
opt <- parse_args(opt_parser)

if (!dir.exists(opt$output_dir)) dir.create(opt$output_dir, recursive = TRUE)

source(file.path(opt$project_dir, "utils", "io.R"))
source(file.path(opt$project_dir, "utils", "plot.R"))


message(paste("\n==================== Processing sample:", opt$sample_name, "===================="))
# load the raw data generated by 01_preprocessing.R
seur_obj <- readRDS(opt$input_rds)

# calculate Mitochondrial Percentage!
seur_obj[["percent.mt"]] <- PercentageFeatureSet(seur_obj, pattern = "^MT-")

message("Generating unfiltered QC plots...")
vln_unfiltered <- create_qc_violin_plot(seur_obj, c("nFeature_RNA", "nCount_RNA", "percent.mt"), paste("Unfiltered -", opt$sample_name))
safe_save_plot(vln_unfiltered, file.path(opt$output_dir, paste0(opt$sample_name, "_01_qc_unfiltered")), w = 15, h = 5)

# pre filtering to speed up doublet finder in later stage
message("Pre-filtering obvious empty droplets...")
seur_obj <- subset(seur_obj, subset = nFeature_RNA > 200 & nFeature_RNA < 10000 & percent.mt < 50)


# =========================================================================
# normalization and dimensionality reduction
# =========================================================================

if (isTRUE(opt$use_sct)) {
  message("Running SCTransform v2...")
  seur_obj <- SCTransform(seur_obj, vars.to.regress = "percent.mt", method = "glmGamPoi", vst.flavor = "v2", verbose = FALSE)
  seur_obj <- RunPCA(seur_obj, assay = "SCT", npcs = 30, verbose = FALSE)
} else {
  message("Running Standard LogNormalize...")
  seur_obj <- NormalizeData(seur_obj) %>% 
    FindVariableFeatures() %>% 
    ScaleData(vars.to.regress = "percent.mt") %>% 
    RunPCA(npcs = 30, verbose = FALSE)
}

seur_obj <- FindNeighbors(seur_obj, dims = 1:30) %>% 
  FindClusters() %>% 
  RunUMAP(dims = 1:30, umap.method = "uwot", metric = "cosine")


# =========================================================================
# doublet finder
# =========================================================================

message("Running DoubletFinder...")

# DoubletFinder needs to know the optimal "neighborhood size" (pK) to search for doublets.
# paramSweep runs the algorithm across many different potential parameter combinations to find the best fit for this specific sample.
sweep.res <- paramSweep(seur_obj, PCs = 1:20, sct = isTRUE(opt$use_sct))
sweep.stats <- summarizeSweep(sweep.res, GT = FALSE)

# this calculates the "BCmvn" (Bimodality Coefficient). It mathematically scores how well each pK value separated doublets from singlets.
bcmvn <- find.pK(sweep.stats)
pK <- as.numeric(as.character(bcmvn$pK[which.max(bcmvn$BCmetric)])) # automatically finds highest BCmetric score

# A "homotypic" doublet is when two cells of the EXACT SAME type stick together.
annotations <- as.character(Idents(seur_obj))
homotypic.prop <- modelHomotypic(annotations)
nExp_poi.adj <- round(round(opt$doublet_rate * ncol(seur_obj)) * (1 - homotypic.prop)) #nExp_poi.adj is the exact number of "heterotypic" (two different cell types stuck together) doublets we want the algorithm to chop out.

# this creates the artificial doublet
seur_obj <- doubletFinder(seur_obj, PCs = 1:20, pN = 0.25, pK = pK, nExp = nExp_poi.adj, reuse.pANN = FALSE, sct = isTRUE(opt$use_sct))
DF_class <- grep("DF.classifications", colnames(seur_obj@meta.data), value = TRUE)[1]

# Plot doublets before removal
doublet_plot <- DimPlot(seur_obj, reduction = "umap", group.by = DF_class, cols = c("Doublet" = "#e35473", "Singlet" = "#54cdeb")) + 
  ggtitle(paste("Doublets -", opt$sample_name))
safe_save_plot(doublet_plot, file.path(opt$output_dir, paste0(opt$sample_name, "_02_doublets")), w = 8, h = 6)

# Keep only singlets
seur_obj <- seur_obj[, seur_obj@meta.data[[DF_class]] == "Singlet"]


# =========================================================================
# final QC
# =========================================================================

# 1. > min_features: Removes empty droplets that only captured ambient RNA.
# 2. < max_features: Removes massive multiplets that DoubletFinder might have missed.
# 3. < max_mt: Removes dead or dying cells where the cell membrane broke and only hardy mitochondrial RNA survived.
message(paste("Applying strict Final QC: Min Features >", opt$min_features, "| Max Features <", opt$max_features, "| Max MT <", opt$max_mt))
seur_obj <- subset(seur_obj, subset = nFeature_RNA > opt$min_features & nFeature_RNA < opt$max_features & percent.mt < opt$max_mt)


vln_final <- create_qc_violin_plot(seur_obj, c("nFeature_RNA", "nCount_RNA", "percent.mt"), paste("Final Clean -", opt$sample_name))
safe_save_plot(vln_final, file.path(opt$output_dir, paste0(opt$sample_name, "_03_qc_final")), w = 15, h = 5)


seur_obj@misc$processed_with_sct <- isTRUE(opt$use_sct)
output_file <- file.path(opt$output_dir, paste0(opt$sample_name, "_clean.rds"))
saveRDS(seur_obj, output_file)

message(paste("Successfully saved clean object to:", output_file))